apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  namespace: an
  labels:
     app: nodeapp
     type: front-end
spec:
  template:
     metadata:
       name: nodejsapp-pod
       labels: 
         app: nodejsapp
         type: front-end
     spec:
         containers:
           - name: nodejsapp-erp
             image: "jed.ocir.io/axnfm4jb3i73/groundx_fe_uat_an:v21707.2"
             imagePullSecrets:
              -name: ocirsecret
  replicas: 1
  selector:
    matchLabels:
      type: front-end

---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  namespace: an
spec:
  selector:
    app: nodejsapp
  type: LoadBalancer  
  ports:
    - protocol: TCP
      targetPort: 3001
      port: 8081
      nodePort: 30002
