export const Departments ={
  'NEOM Authority Activation Office': '27',
  'Infrastructure Department': '#N/A',
  abdulmohsen: '#N/A',
  Accounting: '13',
  'Air Mobility': '1',
  'Air Mobility - Air Mobility': '1',
  'Air Mobility - Airline': '1',
  'Air Mobility - Airport': '1',
  'Applications, Platform and Data': '#N/A',
  'Assessment and Monitoring': '#N/A',
  Audit: '2',
  'Audit - Audit': '2',
  'Audit-Audit': '2',
  Authority: '27',
  'Authority - Legal': '27',
  'Authority Coordination': '27',
  'Authority Cyber Security Office': '#N/A',
  'Backbone Infrastructure': '#N/A',
  'Board Relations': '3',
  'Board Secretariat': '3',
  'Board Secretariat - Board Secretariat': '3',
  'Building and Engineering Codes': '10',
  'Business Continuity': '#N/A',
  'Business Continuity ': '#N/A',
  'Business Development and Special Projects': '35',
  'Business Partnering': '#N/A',
  'CEO Office': '17',
  'CEO’s Office - NEOM Authority Activation': '17',
  "CEO's Office": '17',
  "CEO's Office - CEO's Office": '17',
  "CEO's Office - NEOM Development Fund": '17',
  'Chief Of Staff Offic': '5',
  'Chief of Staff Office': '5',
  'Chief Of Staff Office - Chief Of Staff Office': '5',
  'Chief Of Staff Office - General Secretariat of NEOM Entities': '5',
  'Chief of Staff Office - Systems and Reporting': '5',
  CISO: '6',
  "CISO - CISO's Office": '6',
  'CISO Islam': '6',
  'CISO Office': '6',
  "CISO's Office": '6',
  'CIT- NEOM MUNICIPAITY SITE': '#N/A',
  'Cloud Services': '#N/A',
  Communications: '7',
  'Communications - Communications': '7',
  Community: '7',
  'Community and Social Responsibility': '7',
  'Community Engagement': '7',
  'Community Recreation': '7',
  'Community Services': '7',
  'Community Services, NEOM Operations': '7',
  'Connectivity and Communication': '7',
  Consultant: '#N/A',
  Contracts: '#N/A',
  "COO's Office - Human Resources": '#N/A',
  "COO's Office - Marketing & Communications": '#N/A',
  "COO's Office - Procurement": '#N/A',
  'Corp. IT - NEOM Shared Services': '37',
  'Corporate Compliance GRC': '15',
  'Corporate Digital Marketing': '24',
  'Corporate Finance': '13',
  'Corporate IT': '#N/A',
  'Corporate IT- Customer Interface': '#N/A',
  'Corporate Services and Asset Development': '#N/A',
  'Corporate Social Responsbility': '#N/A',
  CSR: '45',
  'Social Responsibility':"45",
  
  'Customer & Digital': '40',
  'Customer Interface': '#N/A',
  'Cyber Security': '6',
  CyberSecurity: '6',
  'CYBERSECURITY CONSULTANT ': '6',
  'Cybersecurity Program Office': '6',
  'Data & Business Management Services': '#N/A',
  'Data Access & Privacy': '#N/A',
  Dermalog: '#N/A',
  'Design & Construction': '8',
  'Design and Construction': '8',
  'Design and Construction - Design and Construction': '8',
  'Digital & Strategy': '40',
  'Digital Government': '40',
  'Digital government office': '40',
  'Document Control': '#N/A',
  'Down Stream & Data Analytics': '#N/A',
  'Down Stream & Data Analytics-Energy': '#N/A',
  'Down stream and data analytics': '#N/A',
  'Down Stream Data Analytics': '#N/A',
  Education: '9',
  'Education K-12': '9',
  'Education, Research & Innovation': '9',
  'Education, Research and Innovation': '9',
  'Education, Research and Innovation - EC-12': '9',
  'Education, Research and Innovation - Global Programs': '9',
  'Education, Research and Innovation - NEOM U': '9',
  'Employee Relations': '#N/A',
  Energy: '11',
  'Energy, Food & Water': '11',
  'Energy, Water & Food - Energy': '11',
  'Energy, Water & Food - Food': '11',
  'Energy, Water & Food - Water': '11',
  'Energy, Water and Food - Water': '11',
  'Energy-Down Stream & Data Analytics': '11',
  'Engineer -NEOM Operations/FM': '10',
  'Engineering & Technical Services': '10',
  'Engineering & Technical Services-Cost Estimation': '10',
  'Engineering and Technical Services': '10',
  'Engineering and Technical Services - Cost Estimation': '10',
  'Enterprise and Technical Services': '36',
  'Entertainment & Culture': '25',
  'Entities Governance': '#N/A',
  Environment: '12',
  'Environment - Environment': '12',
  'Environment - Environment Quality': '12',
  'Environment - Governance, Strategy and Policy': '12',
  'Environment - Land Conservation and Management': '12',
  'Environment - Sustainable Developments': '12',
  'Environment Quality': '12',
  'Environment Quality & Sustainability': '12',
  'Environmental Assessment Consultant': '12',
  'Environmental Information Management': '12',
  ERI: '9',
  ESCD: '#N/A',
  Facilities: '#N/A',
  'Facilities Management': '#N/A',
  'Facilities Planning': '#N/A',
  'Facilities Planning Division': '#N/A',
  Fahad: '#N/A',
  Finance: '13',
  'Finance - Accounting': '13',
  'Finance - Corporate Finance': '13',
  'Finance - Finance': '13',
  'Finance - Financial Planning & Analysis': '13',
  'Finance - Strategy Finance Planning': '13',
  'Finance-Accounting': '13',
  'Financial Planning  Analysis': '13',
  'Financial Planning %26 Analysis': '13',
  'Financial Planning & Analysis': '13',
  'Financial Planning, Analysis': '13',
  'Financial Services': '13',
  FNRCO: '#N/A',
  Food: '14',
  'Food-Business Strategy': '14',
  'FP&A': '#N/A',
  General: '#N/A',
  GIS: '#N/A',
  'Goverment Affairs': '16',
  Governance: '16',
  'Governance, Risk & Compliance': '15',
  'Governance, Strategy and Policy': '15',
  'Government Affairs': '16',
  'Government Affairs - Business and Executive Support': '45',
  'Government Affairs - Community and Social Responsibility': '45',
  'Government Affairs - Digital Governme': '16',
  'Government Affairs - Digital Government': '16',
  'Government Affairs - Government Affairs': '16',
  'Government Affairs - Government Operations': '16',
  'Government Affairs - Government Relations': '16',
  'Government Affairs - Government Services & Operations': '16',
  'Government Affairs - Public Safety': '16',
  'Government Affairs - Regional Project': '16',
  'Government Affairs - Regional Projects': '16',
  'Government Affairs - Strategic Partnerships': '16',
  'Government Operations': '16',
  'Government Relations': '16',
  GRC: '15',
  'Ground X': '17',
  'Ground X - Ground X': '17',
  'Gulf of Aqaba': '18',
  'Gulf of Aqaba - Gulf of Aqaba': '18',
  'Gulf of Aqaba Proponent': '18',
  'Health  Well Being & Biotech': '20',
  'Health & Safety': '20',
  'Health & wellbeing': '20',
  'Health and Wellbeing': '20',
  'Health Programs and Wellness Resorts': '20',
  'Health Provision and Centers of Excellence': '20',
  'Health Provisions & Center of Excellence': '20',
  'Health Safety & Environment': '20',
  'Health, Well-Being & Biotech': '20',
  'Health, Well-Being & Biotech - Health, Well-Being & Biotech': '20',
  'Health, Well-Being & Biotech - Operations (Infrastructure)': '20',
  'Hotel Development': '21',
  'Hotel Development ': '21',
  'Hotel Development - Hotel Development': '21',
  'Hotel Services Sector': '21',
  'Human Resources': '#N/A',
  'Hydrogen & e-Fuels': '26',
  'Hydrogen & Green Fuels': '26',
  'Industry Learning': '25',
  'Information Technology': '40',
  'Information Technology - Digital Applications': '40',
  'Infrastructure and Operations': '40',
  'Innovation Lead, Hydrogen and e-Fuels Energy Sector': '26',
  Integration: '#N/A',
  'Internal Audit': '2',
  'Internal Audit ': '2',
  'Internal Security': '36',
  IT: '40',
  'IT SAP': '40',
  'IT Shared Services': '40',
  'IT Strategy and Portfolio Management': '40',
  'Land Mobility': '22',
  'Land Mobility - Land Mobility': '22',
  'Land Mobility - Mobility Planning and Integration': '22',
  Legal: '23',
  'Legal - Legal': '23',
  'Legal-Legal': '23',
  'Logistic Project': '#N/A',
  Logistics: '#N/A',
  'Logistics Operations': '#N/A',
  'Managed by IT': '40',
  Management: '#N/A',
  Marketing: '24',
  'Marketing - Brand': '24',
  'Marketing - Marketing': '24',
  'Marketing - Regions': '24',
  'Marketing - Sectors': '24',
  'Marketing & Communications': '24',
  'Marketing and Communications': '24',
  'Master Plans Management': '#N/A',
  MECF: '#N/A',
  Media: '25',
  'Media ': '25',
  'Media - Siobhan Berry': '25',
  'Media & EC': '25',
  'Media Industries': '25',
  'Media Industries Entertainment Culture & Fashion': '25',
  'Media Industries, Entertainment, Culture & Fashion': '25',
  'Media Industries, Entertainment, Culture & Fashion - Media': '25',
  'Media Industries, Entertainment, Culture Fashion': '25',
  'Media, Entertainment, Culture & Fashion': '25',
  'Media, Entertainment, Culture & Fashion - Media': '25',
  'Municipal Affairs': '#N/A',
  Nature: '26',
  'Nature Region': '26',
  'Nature Region - Nature Region': '26',
  NCS: '#N/A',
  'NEOM - Community Services': '7',
  'NEOM - Projects': '35',
  'NEOM Activation & Authority': '27',
  'NEOM Authority': '27',
  'NEOM Authority - \tAuthority Cyber Security Office': '27',
  'NEOM Authority - Sports': '27',
  'NEOM Authority Activation': '27',
  'NEOM Authority Activation - NEOM Authority Activation': '27',
  'NEOM Authority Activation - NEOM Authority Activation Office': '27',
  'NEOM Authority-Policy and Regulations': '27',
  'NEOM Bay': '#N/A',
  'NEOM Bay - NEOM Bay': '#N/A',
  'NEOM BAY - Projects': '#N/A',
  'NEOM Coastal Region': '26',
  'NEOM Community School': '9',
  'NEOM Community Temp School': '9',
  'NEOM Heritage - NEOM Heritage': '20',
  'NEOM Industrial City': '25',
  'NEOM Industrial City ': '25',
  'NEOM Industrial City & Sea Mobility': '25',
  'NEOM Industrial City & Sea Mobility - Industry': '25',
  'NEOM Industrial City & Sea Mobility - NEOM Industrial': '25',
  'NEOM Industrial City & Sea Mobility - NEOM Industrial City': '25',
  'NEOM Industrial City & Sea Mobility - NIC Development Company': '25',
  'NEOM Industrial City & Sea Mobility - Port/Sea Mobility': '25',
  'NEOM Industrial City & Sea Mobility - Sea Mobility': '25',
  'NEOM Industrial City & Sea Mobility - Supply Chain & Logistics': '25',
  'Neom Interim Authority ​': '27',
  'NEOM Investment Fund': '13',
  'NEOM Investment Fund - Investments': '13',
  'NEOM Investment Fund - NEOM Investment Fund': '13',
  'NEOM Investment Fund - Operations': '13',
  'NEOM Investment Office': '13',
  'NEOM Islands': '30',
  'NEOM Islands - Shushah': '30',
  'NEOM Islands - Sindalah': '30',
  'NEOM Islands-Yuba': '30',
  'Neom Logistics': '#N/A',
  'NEOM Mountain': '43',
  'NEOM Mountain - NEOM Mountain': '43',
  'NEOM Mountain Region': '43',
  'NEOM Municipal Affairs': '16',
  'NEOM Operations': '32',
  'NEOM Operations - Community Services': '32',
  'NEOM Operations - Corporate Services and Asset Development': '32',
  'NEOM Operations - Facilities Managemen': '32',
  'NEOM Operations - Facilities Management': '32',
  'NEOM Operations – Municipal Affairs': '32',
  'NEOM Operations - NEOM Operations': '32',
  'NEOM Operations - Planning & Technical Affairs': '32',
  'NEOM Operations - Planning and Municipal Affairs': '32',
  'NEOM Operations - Public Works and Initiatives Execution': '32',
  'NEOM Operations - Security': '32',
  'NEOM Operations - Technology': '32',
  'NEOM Operations – Technology': '32',
  'NEOM Operations - Waste Management': '32',
  'NEOM Projects': '35',
  'NEOM U': '#N/A',
  'NEOM Zero': '33',
  'NEOM Zero - NEOM Zero': '33',
  'NEOS Marketplace': '24',
  'NEOS Platform': '#N/A',
  NIC: '#N/A',
  'NIC Development': '#N/A',
  'NIC International Tenant Attraction': '#N/A',
  'NIC Procurement': '#N/A',
  'NIC Projects': '#N/A',
  NIF: '#N/A',
  'Nortal company': '#N/A',
  'Operational Procurement': '32',
  Operations: '32',
  'Operations & Municipal Support': '32',
  'Organizational Effectiveness & Design': '8',
  OXAGON: '34',
  People: '#N/A',
  'People Technology': '#N/A',
  Pixxel: '#N/A',
  Planning: '#N/A',
  'Planning & Operations': '32',
  'Planning & Technical Affairs': '16',
  'PMO, HELIOS': '#N/A',
  'Policy and Regulations': '#N/A',
  'Port Corporate': '#N/A',
  'Power System Engineering- Energy': '10',
  'Power Systems & Engineering': '10',
  Procuement: '#N/A',
  Procurement: '#N/A',
  Production: '#N/A',
  Projects: '35',
  'Projects - Backbone': '35',
  'Projects - Backbone Infrastructure': '35',
  'Projects - Compliance': '35',
  'Projects - Engineering and Technical Services': '35',
  'Projects - Enterprise and Technical Services': '35',
  'Projects - Health Safety & Environment': '35',
  'Projects - Logistics': '35',
  'Projects - NEOM Coastal Region': '35',
  'Projects - NEOM Industrial City': '35',
  'Projects - Projects': '35',
  'Projects - The Line': '35',
  'Projects Technical Services': '35',
  'Projects ': '35',
  'Projects-NEOM Coastal Region': '35',
  'Public Safety': '15',
  'Public Safety (Government Affairs)': '16',
  'Public Works & Initiatives Execution': '#N/A',
  'Quality & Excellence': '#N/A',
  'Real Estate - Development Management': '#N/A',
  'Recruiting & Onboarding': '#N/A',
  'Regional Projects Department': '#N/A',
  'Regulatory Affairs & Compliance': '#N/A',
  'Resilience Team': '#N/A',
  RMO: '#N/A',
  SAP: '40',
  'SAP IT': '40',
  Scryanalytics: '40',
  'Sector Coordination': '#N/A',
  Security: '#N/A',
  'Security Business Support Manager': '#N/A',
  'Security Centre of Excellence Manager': '#N/A',
  'Security Operations': '#N/A',
  'Security Programs': '#N/A',
  Services: '36',
  'Services - Services': '36',
  'Shared Services': '37',
  'Shared Services - Accounting': '37',
  'Shared Services - Business Partnering': '37',
  'Shared Services - Corporate IT': '37',
  'Shared Services - Procurement': '37',
  'Shared Services - Shared Services': '37',
  'Shared Services -IT': '37',
  'Sharma Valley': '38',
  'Sharma Valley - Sharma Valley': '38',
  Shushah: '#N/A',
  Sindalah: '#N/A',
  Sport: '39',
  Sports: '39',
  'Sports - Sports': '39',
  Strategy: '#N/A',
  'Strategy & Business': '#N/A',
  'Strategy Office': '#N/A',
  'Strategy Office - Strategy Office': '#N/A',
  'Strategy Office - Strategy Planning': '#N/A',
  Student: '9',
  'Support Media and E&C team': '25',
  'Sustainable Developments': '#N/A',
  'T & D Compute & Innovation': '40',
  'T&D NEOS': '40',
  TCS: '#N/A',
  'Tech ': '40',
  'Tech & Digital': '40',
  'Tech & Digital - Delivery': '40',
  'Tech & Digital SAP': '40',
  'Tech & Digitall': '40',
  'Tech & Digitl - SAP': '40',
  'Tech and Digital': '40',
  'Tech Ventures & Business Services Team': '40',
  'Technical & Engineering Services': '40',
  'Technical Consultancy': '40',
  'Technical Services': '40',
  'Technology & Digital': '40',
  'Technology & Digital - Information Technology': '40',
  'Technology and Digita': '40',
  'Technology and Digital': '40',
  'Technology and Digital - Applications & Platform': '40',
  'Technology and Digital - Business Services': '40',
  'Technology and Digital - Compute': '40',
  'Technology and Digital - Delivery': '40',
  'Technology and Digital - Emerging Technology': '40',
  'Technology and Digital - Frontier': '40',
  'Technology and Digital - Information Technology': '40',
  'Technology and Digital - Infrastructure (T&D)': '40',
  'Technology and Digital - NEOM Operations': '40',
  'Technology and Digital - NEOS': '40',
  'Technology and Digital - Technology and Digital': '40',
  'Technology and Digital-NEOS': '40',
  'The Line': '41',
  'The Line Facilities Management': '41',
  Tourism: '42',
  'Tourism - Business Development and Special Projects': '42',
  'Tourism - Destination Development': '42',
  'Tourism - Hotel Development': '42',
  'Tourism - Sales and Marketing': '42',
  'Tourism - Tourism': '42',
  'Transmission & Distribution': '#N/A',
  Travel: '42',
  'Upstream & Market Design': '24',
  'Urban Development': '44',
  'Urban Development - Integration': '44',
  'Urban Development - Master Plans Management': '44',
  'Urban Development - SMART and Livability': '44',
  'Urban Development - Urban Development': '44',
  'Urban Development - Urban Planning': '44',
  'Urban Development / Projects': '44',
  'Urban Development ': '44',
  'Urban Planning': '44',
  'Waste Management': '11',
  Water: '11',
  'Water Management': '11',
  'Water Supply': '11',
  'Water Transmission & Distribution': '11',
  'Water-Waste & Treatment': '11',
  Yuba: 0
}

export const Workspace = {
  "1": "Air Mobility",
  "2": "Audit",
  "3": "Board Secretariat",
  "4": "CEO's Office",
  "5": "Chief Of Staff Office",
  "6": "CISO",
  "7": "Communications",
  "8": "Design and Construction",
  "9": "Education, Research and Innovation",
  "10": "Engineering & Technical Services",
  "11": "ENOWA",
  "12": "Environment",
  "13": "Finance",
  "14": "Food",
  "15": "Governance, Risk & Compliance",
  "16": "Government Affairs",
  "17": "Ground X",
  "18": "Gulf of Aqaba",
  "19": "Heritage",
  "20": "Health, Well-Being & Biotech",
  "21": "Hotel Development",
  "22": "Land Mobility",
  "23": "Legal",
  "24": "Marketing",
  "25": "Media Industries, Entertainment, Culture & Fashion",
  "26": "Nature Region",
  "27": "NEOM Interim Authority",
  "28": "NEOM Investment Fund",
  "29": "NEOM Investment Office",
  "30": "NEOM Islands",
  "31": "NEOM Operations",
  "32": "Community Services",
  "33": "NEOM Zero",
  "34": "OXAGON",
  "35": "Projects",
  "36": "Services",
  "37": "Shared Services",
  "38": "Sharma Valley",
  "39": "Sports",
  "40": "Technology and Digital",
  "41": "THE LINE",
  "42": "Tourism",
  "43": "TROJENA",
  "44": "Urban Development",
  "45":'Social Responsibility'
};